# Site settings
title: "John Peart"
description: "I’m John Peart. I’m a policy professional with an interest in technology, services and diversity. I write about all sorts of things, and I build things in code."
author: "John Peart"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.johnpe.art"

# Assets
image-path: "/assets/images"
css-path: "/assets/styles"
js-path: "/assets/scripts"
social-media-image: "/assets/images/site/social-media.png"
favicon: "/favicon.ico"
favicon-svg: "/assets/images/site/favicon.svg"
favicon-pinned-svg: "/assets/images/site/favicon-pinned-svg.svg"
favicon-large-png: "/assets/images/site/favicon-large-png.png"
theme-colour: "#009fe3"

# <link rel="me" ...>
# Mastodon
mastodon:
  username: "johnpeart"
  instance: "mastodon.social"
  url: "https://mastodon.social/@johnpeart"
  handle: "@johnpeart@mastodon.social"
  
# Bluesky
bluesky:
  username: "johnpe.art"
  instance: "bsky.app"
  url: "https://bsky.app/profile/johnpe.art"
  handle: "@johnpe.art"

# LinkedIn
linkedin:
  url: "https://linkedin.com/in/jrpeart"
  handle: "jrpeart"

# Github
github:
  url:  "https://github.com/johnpeart"
  github-handle:  "johnpeart"
  username: "johnpeart"
  repo: "johnpeart.github.io"
  branch: "main"
  
# Buy Me a Coffee
buymeacoffee:
  url: "https://buymeacoffee.com/johnpeart"
  handle: "johnpeart"

# Gravatar
gravatar:
  url: "https://gravatar.com/johnpeart"
  username: "johnpeart"

# WebMentions
webmentions:
  username: www.johnpe.art
  cache_folder: _data
  cache_bad_uris_for: 5
  collections: true
  legacy_domains:
    - http://johnpe.art
    - http://www.johnpe.art
    - http://jrpeart.com
    - http://www.jrpeart.com
    - http://johnpeart.org
    - http://www.johnpeart.org
  js: false
  syndication:
    mastodon:
      endpoint: https://brid.gy/publish/mastodon
      response_mapping:
        syndication: $.url
        username: $.user.screen_name

# Collections
collections:
  feed:
    output: true
    permalink: /feed/:title.xml
  blogpost:
    output: true
    permalink: /:year/:month/:day/:title/
  weeknotes:
    output: true
    permalink: /weeknote/:year/:month/:day/
  archive:
    output: true
    permalink: /archive/:path/
  about:
    output: true
    permalink: /about/:path/
  now:
    output: true
    permalink: /now/:epoch/
  ideas:
    output: true
  goals:
    output: true
    permalink: /goals/:year/
  wishlist:
    output: false
  podcasts:
    output: false
  manuals:
    output: true
    permalink: /manual/:title/
  reply:
    output: true
    permalink: /reply/:epoch/
  share:
    output: true
    permalink: /share/:epoch/
  note:
    output: true
    permalink: /note/:epoch/
  list:
    output: true
    permalink: /list/:epoch/
  photo:
    output: true
    permalink: /photo/:epoch/
  music:
    output: true
    permalink: /music/:epoch/

defaults:
  - scope:
      type: "blogpost"
    values:
      layout: post
      categories: ["Blogpost"]
  - scope:
      type: "weeknotes"
    values:
      layout: post
      categories: ["Week notes"]
  - scope:
      type: "archive"
    values:
      layout: post
      categories: ["Archived"]
  - scope:
      type: "about"
    values:
      layout: post
      categories: ["About", "Career history"]
  - scope:
      type: "now"
    values:
      layout: post
      categories: ["Now"]
  - scope:
      type: "manuals"
    values:
      layout: post
      categories: ["Manual"]
  - scope:
      type: "note"
    values:
      layout: "post"
      categories: ["Notes"]
  - scope:
      type: "list"
    values:
      layout: "post"
      categories: ["Lists"]
  - scope:
      type: "photo"
    values:
      layout: "post"
      categories: ["Photos"]
  - scope:
      type: "reply"
    values:
      layout: "post"
      categories: ["Reply"]
  - scope:
      type: "share"
    values:
      layout: "post"
      categories: ["Share"]
  - scope:
      type: "music"
    values:
      layout: "post"
      categories: ["Music"]

# Jekyll build settings
remote_theme: johnpeart/theme
permalink: pretty
markdown: kramdown
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
future: false
highlighter: true
sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
