# Site settings
title: "John Peart" 
description: "I’m John Peart. I’m a policy professional with an interest in technology, services and diversity. I write about all sorts of things, and I build things in code."
author: "John Peart"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.johnpe.art"

# Header menu
header-menu:
  - link: "/writing"
    label: "Writing"
  - link: "/photos"
    label: "Photos"
  - link: "/projects"
    label: "Projects"
  - link: "/about"
    label: "About me"
    
# Header menu
footer-menu:
  - link: "/about"
    label: "About me"
  - link: "/writing"
    label: "Writing"
  - link: "/photos"
    label: "Photos"
  - link: "/projects"
    label: "Projects"
  - link: "/goals"
    label: "Goals"
  - link: "/podcast"
    label: "Podcasts"
  - link: "/manuals"
    label: "Manuals"

# Assets
image-path: "/assets/images"
css-path: "/assets/styles"
js-path: "/assets/scripts"
social-media-image: "/assets/images/site/social-media.png"
favicon: "/favicon.ico"
favicon-svg: "/assets/images/site/favicon.svg"
favicon-pinned-svg: "/assets/images/site/favicon-pinned-svg.svg"
favicon-large-png: "/assets/images/site/favicon-large-png.png"
theme-colour: "#009fe3"

# <link rel="me" ...>
# Twitter
twitter-url: "https://twitter.com/johnpeart" # Twitter handle i.e. joebloggs
twitter-handle: "johnpeart" # Twitter handle i.e. joebloggs

# Mastodon
mastodon-url: "https://mastodon.social/@johnpeart"
mastodon-handle: "johnpeart@mastodon.social"
mastodon:
  username: johnpeart
  instance: mastodon.social
  
## LinkedIn
linkedin-url: "https://linkedin.com/in/jrpeart"
linkedin-handle: "jrpeart"
  
# Github
github-url:  "https://github.com/johnpeart"
github-handle:  "johnpeart"

# Editor
github:
  username: "johnpeart"
  repo: "johnpeart.github.io"
  branch: "main"

# WebMentions
webmentions:
  username: www.johnpe.art
  cache_folder: _data
  cache_bad_uris_for: 5
  legacy_domains:
    - http://johnpe.art
    - http://www.johnpe.art
    - http://jrpeart.com
    - http://www.jrpeart.com
    - http://johnpeart.org
    - http://www.johnpeart.org
  js: false
  syndication:
    mastodon: 
      endpoint: https://brid.gy/publish/mastodon
      response_mapping:
        syndication: $.url
        username: $.user.screen_name

# Collections
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/
  pages:
    output: true
    permalink: /:path/
  archive:
    output: true
    permalink: /archive/:path/
    defaults:
      values:
        layout: post
  about:
    output: true
  projects:
    output: true
  goals:
    output: true
    permalink: /goals/:path/
  wishlist:
    output: true
  podcasts:
    output: true
  manuals:
    output: true
    permalink: /manual/:title/
    defaults:
      values:
        layout: manuals/post
             
# Jekyll build settings
remote_theme: johnpeart/theme
permalink: pretty
markdown: kramdown
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
future: false
highlighter: true
sass:
  sass_dir: _sass

# Include these files/folders that are excluded by default
include: 
- "/.well-known"

plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/